/*
 * generated by Xtext 2.11.0
 */
package de.htwdd.sf.beleg


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CustomPrologStandaloneSetup extends CustomPrologStandaloneSetupGenerated {

	def static void doSetup() {
		new CustomPrologStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
